services:
  - type: web
    name: client-request-mcp-server
    env: node
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production